onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/CLK
add wave -noupdate /tb/en_w
add wave -noupdate /tb/en_r
add wave -noupdate /tb/address
add wave -noupdate /tb/DataIn
add wave -noupdate /tb/DataOut
add wave -noupdate /tb/ram
add wave -noupdate /tb/disk
add wave -noupdate /tb/amount
add wave -noupdate /tb/read
add wave -noupdate /tb/write
add wave -noupdate /tb/finish
add wave -noupdate /tb/start
add wave -noupdate /tb/D1/RAM_address
add wave -noupdate /tb/D1/Disk_address
add wave -noupdate /tb/D1/amount
add wave -noupdate /tb/D1/read
add wave -noupdate /tb/D1/write
add wave -noupdate /tb/D1/finish
add wave -noupdate /tb/D1/start
add wave -noupdate /tb/D1/clock
add wave -noupdate /tb/D1/ram
add wave -noupdate /tb/D1/disk
add wave -noupdate /tb/D1/size
add wave -noupdate /tb/D1/data
add wave -noupdate /tb/D1/datadi
add wave -noupdate /tb/D1/datado
add wave -noupdate /tb/D1/datari
add wave -noupdate /tb/D1/dataro
add wave -noupdate /tb/D1/ddataro
add wave -noupdate /tb/D1/ddatado
add wave -noupdate /tb/D1/w
add wave -noupdate /tb/D1/r
add wave -noupdate /tb/D1/wd
add wave -noupdate /tb/D1/wr
add wave -noupdate /tb/D1/rd
add wave -noupdate /tb/D1/rr
add wave -noupdate /tb/D1/started
add wave -noupdate /tb/D1/cond
add wave -noupdate /tb/D1/count
add wave -noupdate /tb/D1/nulldata
add wave -noupdate /tb/D1/CLK
add wave -noupdate /tb/D1/R1/en_w
add wave -noupdate /tb/D1/R1/en_r
add wave -noupdate /tb/D1/R1/address
add wave -noupdate /tb/D1/R1/DataIn
add wave -noupdate /tb/D1/R1/DataOut
add wave -noupdate /tb/D1/R1/clock
add wave -noupdate /tb/D1/R1/adr
add wave -noupdate /tb/D1/R1/CLK
add wave -noupdate /tb/D1/R1/i
add wave -noupdate /tb/D1/D1/Clock
add wave -noupdate /tb/D1/D1/en_w
add wave -noupdate /tb/D1/D1/en_r
add wave -noupdate /tb/D1/D1/address
add wave -noupdate /tb/D1/D1/DataIn
add wave -noupdate /tb/D1/D1/DataOut
add wave -noupdate /tb/D1/D1/adr
add wave -noupdate /tb/D1/D1/CLK
add wave -noupdate /tb/D1/D1/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {227 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
